//! Raw FFI bindings to libaom, generated by `bindgen` at build time.
//!
//! Source headers: `<aom/aom_encoder.h>`, `<aom/aomcx.h>`, `<aom/aom_image.h>`
//! resolved via `pkg-config` (Homebrew, apt, vcpkg). libaom ≥ 3.0 required
//! for `AV1E_SET_TUNE_CONTENT(AOM_CONTENT_SCREEN)` — the screen-content
//! tools (palette coding + IBC) that match Chrome Remote Desktop.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]
#![allow(clippy::missing_safety_doc)]
#![allow(improper_ctypes)]

include!(concat!(env!("OUT_DIR"), "/aom_bindings.rs"));
