//! Raw FFI bindings to libvpx, generated by `bindgen` at build time.
//!
//! Source headers: `<vpx/vpx_encoder.h>`, `<vpx/vp8cx.h>`, `<vpx/vpx_image.h>`
//! resolved via `pkg-config` (Homebrew, apt, vcpkg).
//!
//! The generated file (`$OUT_DIR/vpx_bindings.rs`) is not committed —
//! it regenerates on every fresh build via `build.rs`.

// libvpx symbols and types use C naming. Suppress Rust style lints.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]
#![allow(clippy::missing_safety_doc)]
#![allow(improper_ctypes)]

include!(concat!(env!("OUT_DIR"), "/vpx_bindings.rs"));
