import {
  getSession,
  putSession,
  putTempKey,
  resolveTempKey,
  type KVLike,
  type SessionRecord,
} from './kv-store'
import { allow as rateAllow } from './rate-limiter'
import { corsHeaders, handlePreflight, isAllowedOrigin } from './cors-handler'

interface Env {
  DISCOVERY: KVLike
  /// Shared secret the agent attaches as `Authorization: Bearer <secret>` on
  /// every mutating POST (Phase 04 / H1). Configured via
  /// `wrangler secret put AGENT_REGISTRATION_SECRET`. Lookup endpoints stay
  /// open — the SPA never sees this value. See docs/release-signing.md ...
  /// (no — see plans/260507-0030-security-audit-remediation/phase-04*.md).
  AGENT_REGISTRATION_SECRET?: string
}

const STATE_CHANGING_PATHS = new Set<string>([
  '/api/session/create',
  '/api/session/update',
  '/api/temp-key/create',
  '/api/code/register',
])

// Lookup is open (the SPA has no Bearer) but still rate-limited per IP.
const RATE_LIMITED_PATHS = new Set<string>([
  ...STATE_CHANGING_PATHS,
  '/api/session/lookup',
])

const HEX64 = /^[a-f0-9]{64}$/
// User-typed lookup keys span two shapes today:
//   - Pairing codes  : 8 chars uppercase alnum   (auth::PAIRING_CODE_LEN)
//   - One-time keys  : 16 chars lowercase alnum  (one_time_keys.rs)
// Worker is shape-agnostic — the agent is the trust anchor and registers
// only values it issued. Allow either case across 6-32 alnum to leave room
// for future formats. No special chars (whitespace, hyphens) — the SPA
// strips them client-side.
const LOOKUP_KEY = /^[A-Za-z0-9]{6,32}$/
// Machine-shaped temp keys — 32 lowercase hex generated by `temp-key/create`.
// These are single-use (delete-on-read) so a leaked QR cannot be replayed.
// Human pairing codes / OTKs / lookup_ids never match this regex and stay
// re-resolvable until their KV TTL expires.
const MACHINE_TEMP_KEY = /^[0-9a-f]{32}$/
const TEMP_KEY_BYTES = 16
// Worker accepts up to 24 h — pairing codes still default to 5 min and OTKs
// register with their 30 min lifetime, but permanent-key lookup_ids need a
// long TTL so cross-origin pairing keeps working even when the tunnel URL
// hasn't rotated for hours. Agent re-registers on every TunnelUrlChanged.
const CODE_MAX_TTL_MIN = 24 * 60
const CODE_DEFAULT_TTL_MIN = 5

function jsonResponse(body: unknown, status: number, origin: string | null): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'Content-Type': 'application/json',
      ...corsHeaders(origin),
    },
  })
}

function clientIp(req: Request): string {
  return req.headers.get('cf-connecting-ip') ?? req.headers.get('x-forwarded-for') ?? 'unknown'
}

function generateTempKey(): string {
  const bytes = new Uint8Array(TEMP_KEY_BYTES)
  crypto.getRandomValues(bytes)
  let hex = ''
  for (const b of bytes) hex += b.toString(16).padStart(2, '0')
  return hex
}

function isHexHash(v: unknown): v is string {
  return typeof v === 'string' && HEX64.test(v)
}

// Constant-time string compare. Workers runtime has no `crypto.timingSafeEqual`
// equivalent, so XOR every byte and OR the difference — the loop time is
// dominated by length, which we equalise by always iterating the longer side.
function constantTimeEqual(a: string, b: string): boolean {
  const ab = new TextEncoder().encode(a)
  const bb = new TextEncoder().encode(b)
  const len = Math.max(ab.length, bb.length)
  let diff = ab.length ^ bb.length
  for (let i = 0; i < len; i++) {
    const x = i < ab.length ? ab[i]! : 0
    const y = i < bb.length ? bb[i]! : 0
    diff |= x ^ y
  }
  return diff === 0
}

// Bearer guard for mutating routes (Phase 04 / H1). Returns null when authorised
// or a 401 response when not. AGENT_REGISTRATION_SECRET MUST be configured —
// an unset secret fails closed (refuse all writes) so a misdeployed worker
// cannot accept arbitrary registrations.
function requireWriteAuth(req: Request, env: Env, origin: string | null): Response | null {
  const expected = env.AGENT_REGISTRATION_SECRET
  if (typeof expected !== 'string' || expected.length === 0) {
    // Fail-closed: refuse mutating requests until the operator configures the
    // secret. Returning 503 (not 401) so the agent's retry loop surfaces a
    // clear "worker not provisioned" error instead of "credential invalid".
    return jsonResponse({ error: 'worker not configured' }, 503, origin)
  }
  const header = req.headers.get('authorization') ?? req.headers.get('Authorization')
  if (!header || !header.startsWith('Bearer ')) {
    return jsonResponse({ error: 'unauthorized' }, 401, origin)
  }
  const provided = header.slice(7).trim()
  if (provided.length === 0 || !constantTimeEqual(provided, expected)) {
    return jsonResponse({ error: 'unauthorized' }, 401, origin)
  }
  return null
}

// Phase 04 / H2 — defence against `tunnelUrl: "javascript:..."` etc.
// Only `https:` is accepted; `http:` would also be wrong because the public
// tunnel terminates TLS at Cloudflare. Returns null + the parsed URL only
// when both the parse and the scheme check pass.
function parseHttpsUrl(s: string): URL | null {
  let u: URL
  try {
    u = new URL(s)
  } catch {
    return null
  }
  if (u.protocol !== 'https:') return null
  return u
}

async function readJson<T = unknown>(req: Request): Promise<T | null> {
  try {
    return (await req.json()) as T
  } catch {
    return null
  }
}

async function handleSessionCreate(req: Request, env: Env, origin: string | null): Promise<Response> {
  const body = await readJson<{ apiKey?: unknown }>(req)
  if (!body || !isHexHash(body.apiKey)) {
    return jsonResponse({ error: 'invalid apiKey' }, 400, origin)
  }
  const existing = await getSession(env.DISCOVERY, body.apiKey)
  const record: SessionRecord = {
    tunnelUrl: existing?.tunnelUrl ?? '',
    updatedAt: Date.now(),
  }
  await putSession(env.DISCOVERY, body.apiKey, record)
  return jsonResponse({ ok: true }, 200, origin)
}

async function handleSessionUpdate(req: Request, env: Env, origin: string | null): Promise<Response> {
  const body = await readJson<{ apiKey?: unknown; tunnelUrl?: unknown }>(req)
  if (!body || !isHexHash(body.apiKey) || typeof body.tunnelUrl !== 'string' || body.tunnelUrl.length === 0) {
    return jsonResponse({ error: 'invalid body' }, 400, origin)
  }
  if (parseHttpsUrl(body.tunnelUrl) === null) {
    return jsonResponse({ error: 'tunnelUrl must be a valid https URL' }, 400, origin)
  }
  const record: SessionRecord = {
    tunnelUrl: body.tunnelUrl,
    updatedAt: Date.now(),
  }
  await putSession(env.DISCOVERY, body.apiKey, record)
  return jsonResponse({ ok: true }, 200, origin)
}

async function handleTempKeyCreate(req: Request, env: Env, origin: string | null): Promise<Response> {
  const body = await readJson<{ apiKey?: unknown; expiryMinutes?: unknown }>(req)
  if (!body || !isHexHash(body.apiKey)) {
    return jsonResponse({ error: 'invalid apiKey' }, 400, origin)
  }
  const expiryMins =
    typeof body.expiryMinutes === 'number' && body.expiryMinutes > 0 && body.expiryMinutes <= 60
      ? Math.floor(body.expiryMinutes)
      : 30
  const ttlSecs = expiryMins * 60
  const session = await getSession(env.DISCOVERY, body.apiKey)
  if (!session) {
    return jsonResponse({ error: 'session not found' }, 404, origin)
  }
  const tempKey = generateTempKey()
  await putTempKey(env.DISCOVERY, tempKey, body.apiKey, ttlSecs)
  return jsonResponse({ tempKey, expiresAt: Date.now() + ttlSecs * 1000 }, 200, origin)
}

async function handleCodeRegister(req: Request, env: Env, origin: string | null): Promise<Response> {
  // Agent registers a user-facing pairing code (typed by the human into the
  // SPA login form) so the SPA can resolve which tunnel a given code belongs
  // to, then forward the code to that tunnel for the actual exchange. Without
  // this the cross-origin SPA has no way to route a manually-typed code.
  const body = await readJson<{ apiKey?: unknown; code?: unknown; expiryMinutes?: unknown }>(req)
  if (!body || !isHexHash(body.apiKey)) {
    return jsonResponse({ error: 'invalid apiKey' }, 400, origin)
  }
  if (typeof body.code !== 'string' || !LOOKUP_KEY.test(body.code)) {
    return jsonResponse({ error: 'invalid code shape' }, 400, origin)
  }
  const expiryMins =
    typeof body.expiryMinutes === 'number' &&
    body.expiryMinutes > 0 &&
    body.expiryMinutes <= CODE_MAX_TTL_MIN
      ? Math.floor(body.expiryMinutes)
      : CODE_DEFAULT_TTL_MIN
  const ttlSecs = expiryMins * 60
  const session = await getSession(env.DISCOVERY, body.apiKey)
  if (!session) {
    return jsonResponse({ error: 'session not found' }, 404, origin)
  }
  // Reuse the temp-key index — codes are just human-friendly temp keys with
  // a tighter shape gate. Lookup via /api/session/lookup?k=<code> works
  // unchanged.
  await putTempKey(env.DISCOVERY, body.code, body.apiKey, ttlSecs)
  return jsonResponse({ ok: true, expiresAt: Date.now() + ttlSecs * 1000 }, 200, origin)
}

async function handleSessionLookup(req: Request, env: Env, origin: string | null): Promise<Response> {
  const url = new URL(req.url)
  const k = url.searchParams.get('k')
  if (!k) return jsonResponse({ error: 'missing k' }, 400, origin)
  // Phase 04 / H4 — single-use for machine-shaped keys (32 lowercase hex).
  // Pairing codes / OTKs / lookup_ids stay re-resolvable so a mistype-and-
  // retry doesn't burn the entry on first try. Resolve first, then delete.
  const session = await resolveTempKey(env.DISCOVERY, k)
  if (!session || !session.tunnelUrl) {
    return jsonResponse({ error: 'not found' }, 404, origin)
  }
  if (MACHINE_TEMP_KEY.test(k)) {
    // Best-effort: a failed delete still served the legit lookup; the next
    // attacker request will simply see a delayed expiry.
    try {
      await env.DISCOVERY.delete(`tempkey:${k}`)
    } catch {
      // ignore — see comment above.
    }
  }
  return jsonResponse({ tunnelUrl: session.tunnelUrl }, 200, origin)
}

export default {
  async fetch(req: Request, env: Env): Promise<Response> {
    const url = new URL(req.url)
    const origin = req.headers.get('origin')

    if (req.method === 'OPTIONS') return handlePreflight(origin)

    if (RATE_LIMITED_PATHS.has(url.pathname)) {
      if (STATE_CHANGING_PATHS.has(url.pathname) && origin !== null && !isAllowedOrigin(origin)) {
        return new Response('forbidden', { status: 403 })
      }
      if (!rateAllow(clientIp(req))) {
        return jsonResponse({ error: 'rate limited' }, 429, origin)
      }
    }

    if (req.method === 'POST' && STATE_CHANGING_PATHS.has(url.pathname)) {
      const denial = requireWriteAuth(req, env, origin)
      if (denial) return denial
    }

    if (req.method === 'POST' && url.pathname === '/api/session/create') {
      return handleSessionCreate(req, env, origin)
    }
    if (req.method === 'POST' && url.pathname === '/api/session/update') {
      return handleSessionUpdate(req, env, origin)
    }
    if (req.method === 'POST' && url.pathname === '/api/temp-key/create') {
      return handleTempKeyCreate(req, env, origin)
    }
    if (req.method === 'POST' && url.pathname === '/api/code/register') {
      return handleCodeRegister(req, env, origin)
    }
    if (req.method === 'GET' && url.pathname === '/api/session/lookup') {
      return handleSessionLookup(req, env, origin)
    }

    return new Response('not found', { status: 404 })
  },
}
