[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
xcap = "0.9"
mozjpeg = "0.10"
enigo = { version = "0.6", default-features = false }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
image = { version = "0.25", default-features = false, features = ["jpeg"] }
anyhow = "1"
bytes = "1"
tracing = "0.1"
tokio = { version = "1", features = ["rt", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
